//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EK.Capture.Dicom.DicomToolKit.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EK.Capture.Dicom.DicomToolKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dicom&gt;
        ///    &lt;macro name=&quot;CodeSequenceMacro&quot;&gt;
        ///        &lt;element tag=&quot;(0008,0100)&quot; vt=&quot;1C&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0102)&quot; vt=&quot;1C&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0103)&quot; vt=&quot;1C&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0104)&quot; vt=&quot;1C&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,010F)&quot; vt=&quot;3&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0105)&quot; vt=&quot;3&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0106)&quot; vt=&quot;3&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,010B)&quot; vt=&quot;3&quot;&gt;&lt;/element&gt;
        ///        &lt;element tag=&quot;(0008,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dicom {
            get {
                return ResourceManager.GetString("dicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;dcid id=&apos;270&apos; name=&apos;Observer Type&apos; extensible=&apos;false&apos; version=&apos;20040920&apos;&gt;
        ///      &lt;value&gt;(DCM,121006,Person)&lt;/value&gt;
        ///      &lt;value&gt;(DCM,121006,Device)&lt;/value&gt;
        ///  &lt;/dcid&gt;
        ///  &lt;dcid id=&apos;3629&apos; name=&apos;Procedure Intent&apos; extensible=&apos;true&apos; version=&apos;20030327&apos;&gt;
        ///    &lt;value&gt;(SRT,R-408C3,Diagnostic Intent)&lt;/value&gt;
        ///    &lt;value&gt;(SRT,R-41531,Therapeutic Intent)&lt;/value&gt;
        ///    &lt;value&gt;(SRT,R-002E9,Combined Diagnostic and Therapeutic Procedure)&lt;/value&gt;
        ///  &lt;/dcid&gt;
        ///  &lt;dcid id=&apos;7452&apos; name=&apos;Organizational Roles&apos; exte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
    }
}
